apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
{{- if .Values.global.canary }}
    fabric8.io/expose: "{{ not .Values.global.canary.enable }}"
{{- else }}
    fabric8.io/expose: "true"
{{- end }}
{{- if .Values.service }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.global.service }}
{{ toYaml .Values.global.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
